onboard/config/routes.rb
Rails.application.routes.draw do

  get '/help' => 'static#help'
  get '/contact' => 'static#contact'
  get '/about' => 'static#about'

  root to: redirect('/sign_in')

  devise_for :users, skip: [:sessions], controllers: {
  	registrations: 'users/registrations',
  	confirmations: 'users/confirmations',
  	passwords: 'users/passwords',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_scope :user do
    get '/sign_in' => 'users/sessions#new', as: :new_user_session
    post '/sign_in' => 'users/sessions#create', as: :user_session
    delete '/sign_out' => 'users/sessions#destroy', as: :destroy_user_session
    get '/dash' => 'dashboard#index'
    get '/search_app' => 'apps#search_app'
    get '/search_poc' => 'point_of_contacts#search_poc'
    put '/change_status' => 'apps#change_status'

    resources :staffs
    resources :apps
    resources :point_of_contacts
  end



  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

onboard/app/models/point_of_contact.rb
class PointOfContact < ApplicationRecord
  include DashboardScope
  
  has_and_belongs_to_many :apps, dependent: :delete
  has_one :assignee, class_name: 'App', foreign_key: :assignee_id, dependent: :nullify
  has_one :reporter, class_name: 'App', foreign_key: :reporter_id

  validates :first_name, presence: true
  validates :last_name, presence: true, uniqueness: { scope: :first_name }
  validates :email, presence: true, uniqueness: true, 
  			email: { mx: true, domain: true, ban_disposable_email: true }

  default_scope { order(last_name: :asc) }
  
  max_paginates_per 100  
end

onboard/app/controllers/point_of_contacts_controller.rb
class PointOfContactsController < ApplicationController
  include AjaxParamsConcern
  before_action :authenticate_user!
  before_action :set_point_of_contact, only: [:show, :edit, :update]
  after_action :verify_authorized, except: :search_poc

  def index
  	@point_of_contacts = search_term? ? 
      PointOfContact.where('email LIKE ? or first_name LIKE ? or last_name LIKE ?', 
        lowercase_name, lowercase_name, lowercase_name).page(params[:page]) :
         PointOfContact.page(params[:page])
  	authorize PointOfContact
  end

  def show
  	authorize @point_of_contact
    @own = @point_of_contact.apps
    @reporting = App.all_reporter_apps(@point_of_contact.id)
    @assigned = App.all_assignee_apps(@point_of_contact.id)
  end

  def new
  	@point_of_contact = PointOfContact.new
  	authorize @point_of_contact
  end

  def create
  	@point_of_contact = PointOfContact.new(permitted_params)
  	authorize @point_of_contact

  	if @point_of_contact.save
  	  flash[:success] = t('onboard.controllers.point_of_contact.create.success')
  	  redirect_to point_of_contact_path(@point_of_contact)
  	else
  	  flash[:error] = t('onboard.controllers.point_of_contact.create.failure')
  	  render :index
  	end
  end

  def destroy
  	point_of_contact = PointOfContact.find(params[:id])
  	authorize point_of_contact
  	
    App.replace_delete_reporter(point_of_contact.id)
  	if point_of_contact.destroy
  	  flash[:success] = t('onboard.controllers.point_of_contact.destroy.success')
  	  redirect_to point_of_contacts_path
  	else
  	  flash[:error] = t('onboard.controllers.point_of_contact.destroy.failure')
  	  render :index
  	end
  end

  def edit
  	authorize @point_of_contact
  end

  def update
  	authorize @point_of_contact

  	if @point_of_contact.update(permitted_params)
  	  flash[:success] = t('onboard.controllers.point_of_contact.udpate.success')
  	  redirect_to point_of_contact_path(@point_of_contact)
  	else
  	  flash[:error] = t('onboard.controllers.point_of_contact.udpate.failure')
  	  render :index
  	end
  end

  def search_poc
    @pocs = PointOfContact.where("LOWER(email) LIKE ? OR LOWER(first_name) LIKE ? OR LOWER(last_name) LIKE ?",
       "%#{search_term_lower}%", "%#{search_term_lower}%", "%#{search_term_lower}%")
    respond_to do |format|
      format.html
      format.json { render json: @pocs }
    end
  end

  private

  def permitted_params
  	params.require(:point_of_contact).permit(:first_name, :last_name, :email, :phone, :department)
  end

  def set_point_of_contact
  	@point_of_contact = PointOfContact.find(params[:id])
  end

end

onboard/app/helpers/point_of_contacts_helper.rb
module PointOfContactsHelper
  def present_apps(own, reporting, assigned)
  	own.present? || reporting.present? || assigned.present?
  end
end

onboard/app/views/point_of_contacts/_app_table.html.erb
<% apps.each do |app| %>
  <tr class="cursor" data-link="<%= app_path(app)%>">
	  <td><%= app.name %></td>
	  <td><%= app.jira_ticket_id %></td>
	  <td><%= app.app_url %></td>
  </tr>
<% end %>

onboard/app/views/point_of_contacts/_poc_search_form.html.erb
  <%= form_for point_of_contacts_path, method: :get do |f| %>
    <row class="form-search">
      <div class="col-md-12">
        <%= f.text_field :search_term,  class: 'poc-search-input', placeholder: "First Name, Last Name or Email. Wildcard '%' accepted." %>
      </div>
    </row>
    <row>
      <div class="col-md-4 poc-search">
        <%= f.submit "Search", class: "btn btn-lg btn-primary show-btn", method: :get %>
        <%= link_to 'Reset', point_of_contacts_path, class: "btn btn-lg btn-primary show-btn", method: :get %>
      </div>
    </row>
  <% end %>

onboard/app/views/point_of_contacts/_search_table.html.erb
<% pocs.each_with_index do |poc, index| %>
	<% if index % 2 == 0 %>
	  <tr  class="info cursor" data-link="<%= point_of_contact_path(poc)%>">
	<% else %>
	  <tr class="cursor" data-link="<%= point_of_contact_path(poc)%>">
	<% end %>
    <td><%= poc.last_name %></td>
    <td><%= poc.first_name %></td>
    <td><%= poc.email %></td>
    <td><%= poc.department %></td>
  </tr>
<% end %>

onboard/app/views/point_of_contacts/_table.html.erb
<row>
  <div class="col-md-12">
    <table class="table table-default">
      <tbody class="show-td">
        <tr>
          <td class="bold">First Name</td>
          <td><%= poc.first_name %></td>
        </tr>
        <tr>
          <td class="bold">Last Name</td>
          <td><%= poc.last_name %></td>
        </tr>
        <tr>
          <td class="bold">Email</td>
          <td><%= poc.email %></td>
        </tr>
        <tr>
          <td class="bold">Phone</td>
          <td><%= poc.phone %></td>
        </tr>
        <tr>
          <td class="bold">Department</td>
          <td><%= poc.department %></td>
        </tr>
      </tbody>
    </table>
  </div>
</row>

onboard/app/views/point_of_contacts/index.html.erb
<div class="poc-bg">
  <h2 class="show-header">Point Of Contacts</h2>
  <%= render 'poc_search_form' %>
  <row>
    <div class="col-md-12">
      <hr>
    </div>
  </row>
  <row>
    <div class="col-md-5">
      <h3 class="show-header poc-header-table">Contacts</h3>
    </div>
  </row>
  <table class="table table-hover">
    <thead class="bold">
      <tr>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Email</th>
        <th>Department</th>
      </tr>
    </thead>
    <tbody>
     <%= render 'search_table', pocs: @point_of_contacts %>
    </tbody>
  </table>
  <%= paginate @point_of_contacts %>
</div>

onboard/app/views/point_of_contacts/show.html.erb
<div class="show-bg">
 <row>
    <div class="col-md-9" >
      <h1 class="show-header show-header-links"><%= @point_of_contact.first_name %> <%= @point_of_contact.last_name %></h1>
    </div>
    <div class="col-md-offset-1 col-md-2  back_to_dashboard">
      <h6 class="show-header"><%= link_to "Back to the dashboard", dash_path %></h6>
    </div>
  </row>
  <%= render 'table', poc: @point_of_contact %>
  <row>
    <div class="col-md-5">
      <h2 class="show-header app-header-table">Onboard Applications</h2>
    </div>
  </row>
  <% if present_apps(@own, @reporting, @assigned) %>
    <table class="table table-hover">
      <thead class="show-td bold">
        <th>Application Name</th>
        <th>Jira Ticket Id</th>
        <th>Application Url</th>
      </thead>
        <% if @own.present? %>
        <thead>
          <tr>
            <th colspan="3" class="info bold app_color">Owned</th>
          </tr>
          </thead>
          <tbody>
          <%= render 'app_table', apps: @own %>
          </tbody>
        <% end %>
        <% if @reporting.present? %>
         <thead>
          <tr>
            <th colspan="3" class="info bold app_color">Reporting</th>
          </tr>
          </thead>
          <tbody>
            <%= render 'app_table', apps: @reporting %>
          </tbody>
        <% end %>
        <% if @assigned.present? %>
        <thead>
          <tr>
            <th colspan="3" class="info bold app_color">Assigned</th>
          </tr>
          </thead>
          <tbody>
             <%= render 'app_table', apps: @assigned %>
          </tbody>
        <% end %>   
    </table>
  <% end %>
  <row>
    <div class="col-md-10 show-header-links">
      <%= link_to edit_point_of_contact_path(@point_of_contact), class: 'btn btn-primary show-btn' do %>
       <h4 class="bold show-btn-margin">Edit Contact</h4>
      <% end %>
      <%= link_to point_of_contact_path(@point_of_contact), method: :delete, class: 'btn btn-primary show-btn', data: { confirm: "You will be deleting this record. Proceed?"} do %>
        <h4 class="bold show-btn-margin">Delete Contact</h4>
      <% end %>
    </div>
  </row>
</div>