onboard/config/routes.rb
Rails.application.routes.draw do

  get '/help' => 'static#help'
  get '/contact' => 'static#contact'
  get '/about' => 'static#about'

  root to: redirect('/sign_in')

  devise_for :users, skip: [:sessions], controllers: {
  	registrations: 'users/registrations',
  	confirmations: 'users/confirmations',
  	passwords: 'users/passwords',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_scope :user do
    get '/sign_in' => 'users/sessions#new', as: :new_user_session
    post '/sign_in' => 'users/sessions#create', as: :user_session
    delete '/sign_out' => 'users/sessions#destroy', as: :destroy_user_session
    get '/dash' => 'dashboard#index'
    get '/search_app' => 'apps#search_app'
    get '/search_poc' => 'point_of_contacts#search_poc'
    put '/change_status' => 'apps#change_status'

    resources :staffs
    resources :apps
    resources :point_of_contacts
  end



  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

onboard/app/views/shared/navigation/_nav_header.html.erb
<nav class="navbar navbar-fixed-top onboard-header">
  <div class="container-fluid">
    <div class="navbar-header">
      <%if user_signed_in? %>
        <a class="navbar-brand cursor" onclick="toggleSidebar()"><span class="glyphicon glyphicon-menu-hamburger nav-open-button"></span></a>
      <% end %>
      <a class="navbar-brand">
      	<h4><%= image_tag('DHS_seal.png', size: '30x30')%>  Onboard Applications</h4>
      </a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">   
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          </ul>
        </li>
      	<li class="li-slight-margin">
           <%= link_to destroy_user_session_path, method: :delete do %> 
              <span class="glyphicon glyphicon-log-out"></span> Sign Out
           <% end %>
        </li>
      <% else%>
        <li>
          <%= link_to new_user_registration_path, method: :get do %> 
            <span class="glyphicon glyphicon-user"></span> Sign Up
          <% end %>
        </li>
        <li class="li-slight-margin">
          <%= link_to new_user_session_path, method: :get  do %> 
            <span class="glyphicon glyphicon-log-in"></span> Sign In
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav> 

onboard/app/views/shared/navigation/_sidebar.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <%= link_to dash_path  do %>
      <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Dashboard
      <% end %>
    </li>
    <li>
      <%= link_to 'Onboard Applications', apps_path %>
    </li>
    <li>
      <%= link_to 'Point of Contacts', point_of_contacts_path %>
    </li>
    <% if user_signed_in? && current_user.admin? %> 
      <li>
        <a href="#AdministratorMenu" data-toggle="collapse" data-parent="#AdministratorMenu" class="admin-sidebar-link" id="admin-sidebar-link">  
          <font>Administrator <i id="admin-icon" class="glyphicon glyphicon-chevron-right glyphicon-arrows"></i></font>
        </a>
      </li>
      <div class="collapse" id="AdministratorMenu" >
        <li data-parent="#AdministratorMenu">
          <%= link_to 'Add Application', new_app_path %>
        </li>
        <li data-parent="#AdministratorMenu">
          <%= link_to 'Add Point Of Contact', new_point_of_contact_path %>
        </li>
      </div>
    <% end %>
    <li>
      <a href="#GeneralMenu" data-toggle="collapse" data-parent="#GeneralMenu" class="general-sidebar-link" id="general-sidebar-link">
         <font>General  <i id="general-icon" class="glyphicon glyphicon-chevron-right glyphicon-arrows"></i></font>
      </a>
    </li>
     <div class="collapse" id="GeneralMenu">
       <li data-parent="#GeneralMenu">
         <%= link_to 'Help', help_path %>
       </li>
       <li data-parent="#GeneralMenu">
         <%= link_to 'Contact Us', contact_path %>
       </li>
       <li data-parent="#GeneralMenu">
         <%= link_to 'About', about_path %>
      </li>
    </div>
  </ul>
</div>