onboard/config/routes.rb
Rails.application.routes.draw do

  get '/help' => 'static#help'
  get '/contact' => 'static#contact'
  get '/about' => 'static#about'

  root to: redirect('/sign_in')

  devise_for :users, skip: [:sessions], controllers: {
  	registrations: 'users/registrations',
  	confirmations: 'users/confirmations',
  	passwords: 'users/passwords',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_scope :user do
    get '/sign_in' => 'users/sessions#new', as: :new_user_session
    post '/sign_in' => 'users/sessions#create', as: :user_session
    delete '/sign_out' => 'users/sessions#destroy', as: :destroy_user_session
    get '/dash' => 'dashboard#index'
    get '/search_app' => 'apps#search_app'
    get '/search_poc' => 'point_of_contacts#search_poc'
    put '/change_status' => 'apps#change_status'

    resources :staffs
    resources :apps
    resources :point_of_contacts
  end



  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

onboard/app/views/apps/_form.html.erb
<%= form_for @app do |f| %>
  <% if @app.errors.any? %>
   <div class="error_explanation">
      <h2><%= pluralize(@app.errors.count, "Error") %></h2>
      <ul>
        <% @app.errors.full_messages.each do |msg| %>
          <li> * <%= msg %></li>    
        <% end %>
      </ul>
   </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %><br />

  <%= f.label :app_url %>
  <%= f.text_field :app_url %><br />

  <%= f.label :user_population %>
  <%= f.text_field :user_population %><br />

  <%= f.label :sso_technology %>
  <%= f.text_field :sso_technology %><br />

  <%= f.label :status %>
  <%= f.text_field :status %><br />

  <%= f.label :epic %>
  <%= f.text_field :epic %><br />

  <%= f.label :jira_ticket_id %>
  <%= f.text_field :jira_ticket_id %><br />

  <%= f.label :app_updated %>
  <%= f.text_field :app_updated %><br />

  <%= f.label :app_created %>
  <%= f.text_field :app_created %><br />

  <%= f.label :resolution %>
  <%= f.text_field :resolution %><br />

   <%= f.label :due %>:
  <%= f.text_field :due %><br />

    <%= f.label :reporter %>
  <%= f.text_field :reporter %><br />

  <%= f.label :assignee %>
  <%= f.text_field :assignee %><br />

  <%= f.submit %>
<% end %>

onboard/app/views/apps/_poc_table.html.erb
<tr class="cursor" data-link="<%= point_of_contact_path(poc)%>">
  <td><%= poc.first_name %></td>
  <td><%= poc.last_name %></td>
  <td><%= poc.email %></td>
</tr>

onboard/app/views/apps/_pocs_table.html.erb
<% pocs.each do | poc| %>
  <tr class="cursor" data-link="<%= point_of_contact_path(poc)%>">
    <td><%= poc.first_name %></td>
    <td><%= poc.last_name %></td>
    <td><%= poc.email %></td>
  </tr>
<% end %>

onboard/app/views/apps/_search_app_form.html.erb
  <%= form_for apps_path, method: :get do |f| %>
    <row class="form-search">
      <div class="col-md-12">
        <%= f.text_field :search_term,  class: 'app-search-app-input', placeholder: "Application Name. Accepts wildcard '%' " %>
      </div>
    </row>
    <row>
      <div class="col-md-4">
        <%= f.submit "Search", class: "btn btn-lg btn-primary show-btn app-search-app-btn", method: :get %>
        <%= link_to 'Reset', apps_path, class: "btn btn-lg btn-primary show-btn app-search-app-btn", method: :get %>
      </div>
    </row>   
  <% end %>

onboard/app/views/apps/_search_table.html.erb
 <% apps.each_with_index do |app, index| %>
     <% if index % 2 == 0 %>
       <tr class="info cursor " data-link="<%= app_path(app)%>">
     <% else%>
       <tr class="cursor " data-link="<%= app_path(app)%>">
     <% end %> 
     <td><%= app.name %></td>
     <td><%= app.jira_ticket_id %></td>
     <td><%= app.app_url %></td>
     <td><%= app.epic %></td>
     <td><span class="jira jira-<%= app.status %>"><%= app.status.upcase %></span></td>
   </tr>
 <% end %>

onboard/app/views/apps/_table.html.erb
<row>
  <div class="col-md-12">
      <input type="hidden" value="<%= app.id %>" id="app-id" >
      <table class="table table-default">
      <tbody class="show-td">
        <tr>
         <td class="bold">Jira Ticket Id:</td>
         <td><%= image_tag("jira.png", size: "25x25")%>  <%= app.jira_ticket_id %></td>
        </tr>
        <tr>
         <td class="bold">Application Url:</td>
         <td><%= link_to app.app_url, app.app_url %></td>
        </tr>
        <tr>
         <td class="bold">SSO Technology:</td>
         <td><%= app.sso_technology %></td>
        </tr>
        <tr>
         <td class="bold">Status:</td>
         <td><span class="display-status jira jira-<%= app.status.downcase %>"><%= app.status.to_s.upcase.gsub(/_/, ' ') %></span>
            <select class="onselect-status">
              <option value="not_started" <%= select_option('not_started', app.status)%>>Not Started</option>
              <option value="in_progress" <%= select_option('in_progress', app.status)%>>In Progress</option>
              <option value="blocked" <%= select_option('blocked', app.status)%>>Blocked</option>
              <option value="completed" <%= select_option('completed', app.status)%>>Completed</option>
              <option value="done" <%= select_option('done', app.status)%>>Done</option>
              <option value="accepted"<%= select_option('accepted', app.status)%>>Accepted</option>
            </select>
            <span class="change-status-link cursor app_color">Change Status</span>
         </td>
        </tr>
        <tr>
         <td class="bold">Created At:</td>
         <td><%= app.app_created %></td>
        </tr>
        <tr>
         <td class="bold">Update At:</td>
         <td><%= app.app_updated %></td>
        </tr>
        <tr>
         <td class="bold">Epic Jira Ticket Id:</td>
         <td><%= image_tag("jira.png", size: "25x25")%> <%= app.epic %></td>
        </tr>
         <tr>
         <td class="bold">Resolution:</td>
         <td><%= app.resolution %></td>
        </tr>
        <tr>
         <td class="bold">Due Date:</td>
         <td><%= app.due %></td>
        </tr>
      </tbody>
      </table>
  </div>
</row>

onboard/app/views/apps/edit.html.erb
<h1> Apps#edit</h1>
<p>Find me in app/views/apps/edit.html.erb</p>

onboard/app/views/apps/index.html.erb
<div class="app-bg">
 <h2 class="show-header">Onboard Applications</h2>
 <%= render 'search_app_form' %>
 <row>
   <div class="col-md-12">
     <hr>
   </div>
 </row>
 <row>
   <div class="col-md-5">
     <h3 class="show-header app-header-table">Applications</h3>
   </div>
 </row>
   <table class="table table-hover">
     <thead>
       <tr>
         <th>Name</th>
         <th>Jira Ticket ID</th>
         <th>Application Url</th>
         <th>Epic Jira Ticket ID</th>
         <th>Status</th>
       </tr>
     </thead>
     <tbody>
       <%= render 'search_table', apps: @apps %>
     </tbody>
   </table>
   <%= paginate @apps %>
</div>

onboard/app/views/apps/new.html.erb
<h1> Apps#new</h1>
<p>Find me in app/views/apps/new.html.erb</p>

onboard/app/views/apps/show.html.erb
<div class="show-bg">
  <row>
    <div class="col-md-9" >
      <h1 class="show-header show-header-links"><%= @app.name %></h1>
    </div>
    <div class="col-md-offset-1 col-md-2 back_to_dashboard" >
      <h6 class="show-header"><%= link_to "Back to the dashboard", dash_path %></h6>
    </div>
  </row>
  <%= render 'table', app: @app %>
  <row>
    <div class="col-md-12">
      <h2 class="show-header poc-header-table">Point Of Contacts</h2>
    </div>
  </row>
  <table class="table table-hover">
    <thead class="show-td bold">
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <thead>
      <% unless @app.point_of_contacts.empty? %>
        <tr>
          <th colspan="3" class="info bold app_color">Owners</th>
        </tr>
        </thead>
        <tbody>
          <%= render 'pocs_table', pocs: @app.point_of_contacts %>
        </tbody>
      <% end %>
      <thead>
      <tr>
       <th colspan="3" class="info bold app_color">Reporter</th>
      </tr>
      </thead>
      <tbody>
        <%= render 'poc_table', poc: @app.reporter %>
      </tbody>
      <% if @app.assignee.present? %>
      <thead>
        <tr>
          <th colspan="3" class="info bold app_color">Assignee</th>
        </tr>
        </thead>
        <tbody>
          <%= render 'poc_table', poc: @app.assignee %>
      <% end %>
      </tbody>
  </table>
  <row>
    <div class="col-md-10 show-header-links">
      <%= link_to edit_app_path(@app), class: 'btn btn-primary show-btn' do %>
       <h4 class="bold show-btn-margin">Edit App</h4>
      <% end %>
      <%= link_to app_path(@app), method: :delete, class: 'btn btn-primary show-btn', data: { confirm: "You will be deleting this record. Proceed?" } do %>
        <h4 class="bold show-btn-margin">Delete App</h4>
      <% end %>
    </div>
  </row>
</div>